version: '3.1'
services:
  mysql:
    container_name: mysql_bd
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root' 
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - my-datavolume:/var/lib/mysql

  mongo:
    container_name: mongo_bd
    restart: always
    image: mongo:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root' 
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - my-datavolume:/var/lib/mongo
volumes:
  my-datavolume:




